---
# Prerequisities
- name: Install prereq
  become: true
  ansible.builtin.apt:
    name: "{{ my_list_1 }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600 # cache repos for 1 hour
  when: ansible_os_family == "Debian"
  tags:
    - packages

# Repo for Ubuntu
- name: Add repo
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:ondrej/php"
    state: present
  when: ansible_distribution == "Ubuntu"
  tags:
    - packages
    - ubuntu

# Repo for Debian (way A)
# - name: Add repo using key from URL
#   become: true
#   deb822_repository:
#     name: php-ondrej
#     types: deb
#     uris: https://packages.sury.org/php/
#     suites: '{{ ansible_distribution_release }}'
#     components: stable
#     architectures: amd64
#     signed_by: https://packages.sury.org/php/apt.gpg
#   when: ansible_distribution == "Debian"
#   tags:
#     - packages
#     - debian

# Repo for Debian (way B)
- name: Add repo using key from URL
  become: true
  when: ansible_distribution == "Debian"
  block:
    - name: Download the gpg key for repo
      ansible.builtin.get_url:
        url: https://packages.sury.org/php/apt.gpg
        dest: /usr/share/keyrings/deb.sury.org-php.gpg

    # - name: Dearmor the key

    - name: Add repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/deb.sury.org-php.gpg] https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
        state: present

# Install LAMP for Debian/Ubuntu
- name: Install Lamp stack
  become: true
  ansible.builtin.apt:
    name: "{{ my_list_2 }}"
    state: present
    update_cache: yes
    # cache_valid_time: 3600 # cache repos for 1 hour
  notify:
    - start apache2
    - start mariadb
  tags:
    - packages
