---
- name: Administartive group playbook
  hosts:
    - ubuntu
  # become: true

  gather_facts: true

  vars_files:
    - vars/secrets.yaml

  vars:
    bg_url: "https://thumbs.dreamstime.com/z/isolated-headshot-african-american-business-woman-ceo-finance-law-attorney-legal-representative-white-background-167982948.jpg"
    bg_dest_filename: bg-office.jpg

  roles:
    - common
    - office
