---
- name: Development group playbook
  hosts:
    - ubuntu
  # become: true

  gather_facts: true

  vars_files:
    - vars/secrets.yaml

  vars:
    bg_url: "https://cdn.wallpapersafari.com/55/73/ghY4rc.jpg"
    bg_dest_filename: bg-dev.jpg

  roles:
    - common
    - dev
