---
# handlers file for lamp01
- name: start apache2
  become: true
  service:
    name: apache2
    state: restarted

- name: start httpd
  become: true
  service:
    name: httpd
    state: restarted

- name: start mariadb
  become: true
  service:
    name: mariadb
    state: restarted
